using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.SqlModels
{
    [Table("custom_attributes")]
    public class CustomAttribute
    {
        [Column("custom_attribute_id")]
        [AutoGenerated]
        public int CustomAttributeId { get; set; }
        [Column("name")]
        public string Name { get; set; }
        [Column("display_name")]
        public string DisplayName { get; set; }
        [Column("product_line_id")]
        public int ProductLineId { get; set; }
        [Column("data_type")]
        public string DataType { get; set; }
    }
}
